### ISSUE TITLE
Only the first grid filter tag is processed

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/SyliusGridBundle#22]
Given the following configuration:
```
    App\Grid\Filter\EntityFilter:
        tags:
            - { name: sylius.grid_filter, type: entity, form_type: App\Form\Type\Grid\Filter\EntityType }
            - { name: sylius.grid_filter, type: foo, form_type: App\Form\Type\Grid\Filter\FooType }
            - { name: sylius.grid_filter, type: bar, form_type: App\Form\Type\Grid\Filter\BarType }
            - { name: sylius.grid_filter, type: baz, form_type: App\Form\Type\Grid\Filter\BazType }
```
Only the `entity` type will be registered.

**Comment by lchrusciel** [comment]
Here https://github.com/Sylius/SyliusGridBundle/blob/master/src/Bundle/DependencyInjection/Compiler/RegisterFiltersPass.php#L35-L40 we should iterate over `$attributes` array instead of taking the first key only. Same is true to the rest of Compliers

**Comment by vvasiloi** [comment]
@lchrusciel That's right. I tested it editing the vendor files before opening the issue and worked on a PR afterwards.

**Comment by vvasiloi** [comment]
@lchrusciel I'm doing the same to the other two compiler passes, will add to the same PR.

**Comment by vvasiloi** [comment]
@lchrusciel done!
