### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by pamil** [Sylius/SyliusGridBundle#29]
The issue to track and coordinate efforts.

**Comment by stloyd** [comment]
@pamil @lchrusciel This can be closed as Symfony 5 is supported already after #34

**Comment by lchrusciel** [comment]
Hey Joseph, thanks for bringing it up :)

**Comment by pamil** [comment]
The build is still failing - https://travis-ci.org/github/Sylius/SyliusGridBundle/builds/718206083

**Comment by pamil** [comment]
Done in #86.
